- nrfx_glue.h
Replace BUILD_ASSERT_MSG() with BUILD_ASSERT() in order for the following PR to proceed:
https://github.com/zephyrproject-rtos/zephyr/pull/23437
> nrfx_glue: Replace BUILD_ASSERT_MSG() with BUILD_ASSERT()

- drivers/nrf_radio_802154/rsch/nrf_802154_rsch.c
When the nRF 802.15.4 radio driver is used in multiprotocol scenarios,
it might happen that the arbiter revokes access to the RADIO peripheral
and it is not notified to the higher layer, e.g. because of other preconditions
being denied already. This patch enables the arbiter to complete its processing
even if the higher layer is not notified about it.
> drivers: nrf_radio_802154: Ensure RAAL finishes its processing

- drivers/nrf_radio_802154/CMakeLists.txt
Signed-off-by: Pegza, Jakub <Jakub.Pegza@nordicsemi.no>
Shall be merged after https://github.com/zephyrproject-rtos/zephyr/pull/29443
> drivers: nrf_radio_802154: Add buffer config

- drivers/nrf_802154_serialization/src/platform/zephyr/nrf_802154_spinel_backend_ipc.c
IPM callback make use of system work queue. If an application makes
a radio request also from system work queue the deadlock occures.
This commit fixes the bug by using dedicated work queue for IPM
callbacks.
Signed-off-by: Lukasz Maciejonczyk <lukasz.maciejonczyk@nordicsemi.no>
> drivers: Fix deadlock in IPC communication

- drivers/nrf_802154_serialization/src/platform/zephyr/nrf_802154_spinel_backend_ipc.c
Signed-off-by: Hubert Miś <hubert.mis@nordicsemi.no>
> drivers: 802154_serialization: Update RPMsg Service include path

- drivers/nrf_802154/driver/CMakeLists.txt
- drivers/nrf_802154/driver/include/nrf_802154.h
- drivers/nrf_802154/driver/include/nrf_802154_const.h
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_ack_timeout.c
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_csma_ca.c
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_delayed_trx.c
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_delayed_trx.h
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_precise_ack_timeout.c
- drivers/nrf_802154/driver/src/nrf_802154.c
- drivers/nrf_802154/driver/src/nrf_802154_core.c
- drivers/nrf_802154/driver/src/nrf_802154_core.h
- drivers/nrf_802154/driver/src/nrf_802154_notification.h
- drivers/nrf_802154/driver/src/nrf_802154_notification_direct.c
- drivers/nrf_802154/driver/src/nrf_802154_notification_swi.c
- drivers/nrf_802154/driver/src/nrf_802154_request.h
- drivers/nrf_802154/driver/src/nrf_802154_request_direct.c
- drivers/nrf_802154/driver/src/nrf_802154_request_swi.c
- drivers/nrf_802154/driver/src/nrf_802154_trx.c
- drivers/nrf_802154/driver/src/nrf_802154_trx_ppi.c
- drivers/nrf_802154/serialization/include/host/nrf_802154.h
- drivers/nrf_802154/serialization/include/host/nrf_802154_callouts.h
- drivers/nrf_802154/serialization/include/host/nrf_802154_types.h
- drivers/nrf_802154/serialization/src/include/nrf_802154_spinel_datatypes.h
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_app.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_dec_app.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_dec_net.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_net.c
- drivers/nrf_802154/sl/include/rsch/nrf_802154_rsch.h
This commit updates the nRF 802.15.4 radio driver to feature
the latest changes.
sdk-nrf-802154 commit: 9307dc01053c7f4ddb3081984a72a6d454ec8681
> drivers: nrf_802154: Update the IEEE 802.15.4 component

- nrfx/drivers/src/nrfx_usbd.c
Ensure that total number of bytes transferred by DMA is even before USBD is disabled. This prevents bad DMA request from happening on first DMA after re-enabling DMA if the total bytes transferred was odd.
The bad DMA request was observed as SPU FLASHACCERR when building for nrf5340dk_nrf5340_cpuapp_ns target. The bad DMA request would manifest itself as device failing to reconnect after USB cable was reconnected. The issue was especially visible with CDC ACM sample because SET LINE CODING request has 7 bytes payload.
> nrfx_usbd: Prevent spurious bad DMA request

- drivers/nrf_802154/common/include/nrf_802154.h
- drivers/nrf_802154/common/include/nrf_802154_config.h
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_security_pib.h
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_security_pib_ram.c
- drivers/nrf_802154/driver/src/nrf_802154.c
- drivers/nrf_802154/driver/src/nrf_802154_notification_swi.c
- drivers/nrf_802154/serialization/src/include/nrf_802154_spinel_datatypes.h
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_app.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_dec_app.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_dec_net.c
> nrf_802154: rev aaff0ad8570c2f7069ae9fc8f60153941275a6ae

- drivers/nrf_802154/common/include/nrf_802154.h
- drivers/nrf_802154/common/include/nrf_802154_types.h
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_csma_ca.c
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_delayed_trx.c
- drivers/nrf_802154/driver/src/nrf_802154.c
- drivers/nrf_802154/driver/src/nrf_802154_core.c
- drivers/nrf_802154/driver/src/nrf_802154_pib.c
- drivers/nrf_802154/driver/src/nrf_802154_pib.h
- drivers/nrf_802154/driver/src/nrf_802154_trx.c
- drivers/nrf_802154/driver/src/nrf_802154_types_internal.h
- drivers/nrf_802154/serialization/src/include/nrf_802154_spinel_datatypes.h
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_app.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_dec_net.c
> nrf_802154: rev 1bff96a60a6f40dae3a9262cb4a828035008df21

- drivers/nrf_802154/common/include/nrf_802154_callouts.h
- drivers/nrf_802154/common/include/nrf_802154_common_utils.h
- drivers/nrf_802154/common/include/nrf_802154_config.h
- drivers/nrf_802154/common/include/nrf_802154_nrfx_addons.h
- drivers/nrf_802154/common/include/nrf_802154_types.h
- drivers/nrf_802154/common/src/nrf_802154_common_utils.c
- drivers/nrf_802154/driver/src/nrf_802154.c
- drivers/nrf_802154/driver/src/nrf_802154_core.c
- drivers/nrf_802154/driver/src/nrf_802154_notification.h
- drivers/nrf_802154/driver/src/nrf_802154_notification_direct.c
- drivers/nrf_802154/driver/src/nrf_802154_notification_swi.c
- drivers/nrf_802154/serialization/src/include/nrf_802154_nrfx_addons.h
- drivers/nrf_802154/serialization/src/include/nrf_802154_spinel_datatypes.h
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_dec_app.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_net.c
> nrf_802154: rev ff6aba3a0496b36a8ffb25b97233187e721400af

- nrfx/drivers/src/nrfx_uarte.c
Break 2 busy wait loops with a very small delay to avoid the simulation hanging.
These delays have no effect on real HW as they are conditionally compiled.
The minor `if` refactoring is to simplify the amount of conditions but yield the same result, while only applying the delay for simulation if the loop needs to iterate.
> drivers: nrfx_uarte: Fixes for simulation

- drivers/nrf_802154/common/include/nrf_802154.h
- drivers/nrf_802154/driver/src/mac_features/nrf_802154_delayed_trx.c
- drivers/nrf_802154/driver/src/nrf_802154.c
- drivers/nrf_802154/serialization/src/include/nrf_802154_spinel_datatypes.h
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_app.c
- drivers/nrf_802154/serialization/src/nrf_802154_spinel_dec_net.c
> nrf_802154: rev e45bb47f0a4a43b69d19a145bdf15001d67e02dd

- nrfx/hal/nrf_pwm.h
MAXCNT register is present on nRF54 Series, but under different name.
`DNM` until accompanying MDK fix is available
> nrfx: fix support for nRF54 Series in PWM HAL

- nrfs/src/services/nrfs_clock.c
Fix for double response for subscription event.
> nrfs: Fix clock handler

- nrfs/helpers/dvfs_oppoint.c
- nrfs/src/services/nrfs_mram.c
Minor fixes for mram and dvfs services.
Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/75520
> nrfs: fixes for mram and dvfs services

- utils/module.yml.j2
- utils/update_wifi_fw.py
- zephyr/module.yml
The local and remote paths are different.
> nrfwifi: Fix FW blobs path

- drivers/nrf_wifi/bus_if/bal/inc/bal_api.h
- drivers/nrf_wifi/fw_if/umac_if/inc/default/fmac_api.h
- drivers/nrf_wifi/fw_if/umac_if/inc/radio_test/fmac_api.h
- drivers/nrf_wifi/hw_if/hal/inc/hal_api.h
- drivers/nrf_wifi/os_if/inc/osal_api.h
Fix all Doxygen issues found in nrf_wifi.
> nrf_wifi: Fix all Doxygen issues

- drivers/nrf_wifi/fw_if/umac_if/inc/default/fmac_api.h
- drivers/nrf_wifi/fw_if/umac_if/inc/fmac_cmd.h
- drivers/nrf_wifi/fw_if/umac_if/inc/fmac_util.h
- drivers/nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
- drivers/nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_umac_if.h
- drivers/nrf_wifi/fw_if/umac_if/inc/fw/patch_info.h
- drivers/nrf_wifi/fw_if/umac_if/inc/offload_raw_tx/fmac_api.h
- drivers/nrf_wifi/fw_if/umac_if/inc/offload_raw_tx/fmac_structs.h
- drivers/nrf_wifi/fw_if/umac_if/src/cmd.c
- drivers/nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
- drivers/nrf_wifi/fw_if/umac_if/src/event.c
- drivers/nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- drivers/nrf_wifi/fw_if/umac_if/src/offload_raw_tx/fmac_api.c
- drivers/nrf_wifi/fw_if/umac_if/src/rx.c
- drivers/nrf_wifi/fw_if/umac_if/src/tx.c
- drivers/nrf_wifi/hw_if/hal/inc/hal_structs.h
- drivers/nrf_wifi/hw_if/hal/src/hal_api.c
- drivers/nrf_wifi/hw_if/hal/src/hal_interrupt.c
- drivers/nrf_wifi/os_if/inc/osal_api.h
- drivers/nrf_wifi/os_if/inc/osal_ops.h
- drivers/nrf_wifi/os_if/src/osal.c
- utils/update_wifi_fw.py
- zephyr/module.yml
Mainly related to RPU recovery feature.
> wifi: nRF70 SnS fixes

- drivers/nrf_wifi/bus_if/bus/spi/src/spi.c
- drivers/nrf_wifi/fw_if/umac_if/inc/fmac_structs_common.h
- drivers/nrf_wifi/fw_if/umac_if/src/cmd.c
- drivers/nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- drivers/nrf_wifi/os_if/inc/osal_api.h
- drivers/nrf_wifi/os_if/src/osal.c
Fix a memory leak in regulatory domain handling.
> Fix reg memleak

- drivers/nrf_wifi/hw_if/hal/src/hal_interrupt.c
Build warnings when LPM is disabled.
> wifi: Fix no LPM build

- drivers/nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
- utils/module.yml.j2
- utils/update_wifi_fw.py
- zephyr/module.yml
Pull in all the recent updates done to firmware and corresponding rpu shared file changes.
> nrf_wifi : Update to latest firmware

- utils/update_blobs.py
- zephyr/module.yml
See https://github.com/zephyrproject-rtos/zephyr/issues/78642.
> module.yml: Add a SUIT manifest binary blob

- drivers/nrf_wifi/fw_if/umac_if/src/event.c
- drivers/nrf_wifi/hw_if/hal/inc/hal_structs.h
- drivers/nrf_wifi/hw_if/hal/src/hal_api.c
> wifi: Fix build failures

- drivers/nrf_wifi/os_if/inc/osal_api.h
Fix the unknown parameter build error.
> nrf_wifi: Fix doxygen build errors

- nrfx/drivers/src/nrfx_spim.c
Extend workaround for nrf54lm20 which requires different hidden register to be used and it shall be applied for any configuration.
> nrfx: nrfx_spim: Extend NRF54L ERRATA 8 workaround for nrf54lm20

- nrfx/drivers/src/nrfx_nvmc.c
- nrfx/drivers/src/nrfx_rramc.c
Fix build with disabled assertions on clang.
> nrfx: drivers: nvmc: declare functions as unused
