CMakeLists.txt
nrfx_glue.h

Two minor corrections related to the clean up of nrfx inclusions in the main Zephry repo.
**CMakeLists.txt: Remove nrfx/hal from list of include directories**
HAL headers are not supposed to be included directly, but only with
their names prepended with the hal/ directory (so that the inclusion
of a HAL header clearly differs from the inclusion of a driver one).
**nrfx_glue.h: Remove inclusion of <kernel.h>**
Remove this inclusion to avoid creating a cycle when nrfx.h is included
from kernel.h via soc.h, what can result in half processed header files
in between and consequently missing definitions.
cc @SebastianBoe

nordic: Clean up nrfx inclusions

---

nrfx/drivers/include/nrfx_i2s.h
nrfx/drivers/src/nrfx_i2s.c

Add the NRFX_I2S_STATUS_TRANSFER_STOPPED flag to the nrfx_i2s driver's
API, to provide the application with a notification when the driver
actually stops the transfer after the nrfx_i2s_stop function is called.
Move also the corresponding update of the driver's state to the point
before the handler function is called, so that it is possible to start
a next transfer directly from the handler function.
This is a temporary patch, needed to proceed with a PR in the main
Zephyr repository that requires such extension of the nrfx_i2s driver.
Same changes will be contained in the next release of nrfx.

nrfx_i2s: Introduce NRFX_I2S_STATUS_TRANSFER_STOPPED flag

---

drivers/nrf_radio_802154/platform/clock/nrf_802154_clock_zephyr.c

Align driver to clock_control using subsys argument to identify
clock source.
zephyr PR:
https://github.com/zephyrproject-rtos/zephyr/pull/21486
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

drivers: nrf_radio_802154: Align to lates changes in clock_control

---

nrfx/drivers/src/nrfx_rtc.c
nrfx/drivers/src/nrfx_timer.c

To avoid warnings about providing an argument of type `uint32_t` (which
is `unsigned int`) where a `long unsigned int` one is expected.

nrfx: Cast `uint32_t` arguments to `unsigned long` in log messages

---

nrfx_glue.h

Use __ASSERT_NO_MSG directly, not through the assert macro that comes
from libc, as the definition of the latter might be different when
some specific libc version is used, and this could generate troubles.

nrfx_glue: Define NRFX_ASSERT as __ASSERT_NO_MSG

---

nrfx_config_nrf5340_application.h
nrfx_config_nrf9160.h

For peripherals with only one type of access available (either secure
or non-secure), the common symbol translation scheme cannot be used
as it leads to mapping to non-existing symbols (e.g. NRF_FICR_NS).
Instead, use fixed translations for these symbols (e.g. NRF_FICR to
NRF_FICR_S, only for secure images).

nrfx_config: Fix translation of symbols for _S or _NS only peripherals

---

nrfx/drivers/src/nrfx_i2s.c
nrfx/hal/nrf_i2s.h
nrfx_config_nrf5340_application.h
nrfx_config_nrf5340_network.h
nrfx_config_nrf9160.h

This is a follow-up to #26.
Add translations of names with _S and _NS suffixes for peripheral
access symbols that are available for a given chip but were not used
so far in any nrfx HAL or driver, to make the lists of translations
complete and consistent.
This commit corrects also the translation of NRF_I2S symbol for nRF5340
whose name for this SoC contains also the index 0 (so it needs to be
handled similarly like NRF_PDM0 is).

nrfx_config: Add missing _S/_NS symbol translations for nRF5340/nRF9160

---

drivers/nrf_radio_802154/CMakeLists.txt
drivers/nrf_radio_802154/platform/lp_timer/nrf_802154_lp_timer_zephyr.c
drivers/nrf_radio_802154/platform/random/nrf_802154_random_zephyr.c

Enable CSMA/CA support in the radio driver. Implement/rework features in the platform layer needed to make it work.

drivers: nrf_radio_802154: Enable CSMA/CA

---

drivers/nrf_radio_802154/platform/random/nrf_802154_random_zephyr.c

Align with the replacement done in the main Zephyr repository.

nrf_radio_802154: Replace CONFIG_ENTROPY_NAME with DT_LABEL(<rng_node>)

---

nrfx_glue.h
nrfx_log.h

To prevent compilation errors when some C++ elements, like a template
definition, happen to appear in those included files or files included
by them.

nrfx_glue: Move #include directives outside of extern "C" blocks

---

drivers/nrf_radio_802154/CMakeLists.txt
drivers/nrf_radio_802154/nrf_802154_timer_coord.c
drivers/nrf_radio_802154/platform/clock/nrf_802154_clock_zephyr.c

Several improvements for the radio driver:
* Switch clock implementation to Zephyr asychronous clock API,
* Enable ACK timeout feature,
* Enable RX timestamps,
* Enable delayed TX.

drivers: nrf_radio_802154: ACK timeout, RX timestamps, delayed TX

---

nrfx_glue.h

Convert the PWM_NRF5_SW_DEV DT usage to the new DT_INST style macros.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

nrfx_glue: Convert PWM SW device to new DT macros

---

drivers/nrf_radio_802154/platform/random/nrf_802154_random_zephyr.c

Use the label property of the node pointed by "zephyr,entropy" chosen
entry as the name of the entropy device to bind to. The pointed node
does not necessarily need to be a "nordic,nrf-rng" compatible one, what
was incorrectly assumed when CONFIG_ENTROPY_NAME was replaced in commit
5505d0baa66a89848f643120fafad232876df695.

nrf_radio_802154: Use chosen zephyr,entropy to get entropy device

---

nrfx/drivers/src/nrfx_nvmc.c

Fix compilation issue when NRF_TRUSTZONE_NONSECURE is defined.
In this case NRF_UICR is not defined and should not be accessible
from non-secure.
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

nrfx_nvmc: Fix compilation issue NRF_UICR not defined

---

nrfx_glue.h

When CONFIG_BT_CTLR is enabled, NRFX_PPI_CHANNELS_USED_BY_BT_CTLR
references a symbol (z_bt_ctlr_used_nrf_ppi_channels) that is defined
in radio.c, a file that is compiled when both CONFIG_BT_CTLR and
CONFIG_BT_LL_SW_SPLIT are enabled. This commit corrects accordingly
the definition of NRFX_PPI_CHANNELS_USED_BY_BT_CTLR, so that it won't
cause an unresolved reference error.

nrfx_glue: Fix NRFX_PPI_CHANNELS_USED_BY_BT_CTLR definition

---

nrfx_glue.c
nrfx_glue.h

Convert glue code to use C99 types as we intend to deprecate the zephyr
specific integer types.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

nrfx_glue: Convert from Zephyr to C99 types

---

CMakeLists.txt
nrfx_glue.h

This is a follow-up to commit c84263d8ecc7767b25d9abab9502c9e748d045e9.
The same correction that was done for the PPI channels macro needs to
be done also for the PPI groups macro.
This commit reorganizes a bit definitions of these macros in question,
for easier maintenance.

nrfx_glue: Fix NRFX_PPI_GROUPS_USED_BY_BT_CTLR definition

---

drivers/nrf_radio_802154/platform/clock/nrf_802154_clock_zephyr.c

Align with changes in Zephyr to use onoff API instead of clock_control
for clock management. Using clock_control API makes radio driver
initialization fail.
Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

drivers: nrf_radio_802154: Switch to onoff API for clock handling

---

nrfx/hal/nrf_gpio.h

Add special comments that will prevent warnings that would otherwise
appear when compilation is done with the -Wimplicit-fallthrough
options, as the falls through are intentional.
This is a temporary change in a file imported from the nrfx repository
and it is supposed to be overwritten by the next update of nrfx.

nrf_gpio: Prevent warnings about switch cases falling through

---

drivers/nrf_radio_802154/platform/clock/nrf_802154_clock_zephyr.c

hfclk_is_running was used instead of lfclk_is_running in
nrf_802154_clock_lfclk_stop() function.
Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

drivers: nrf_radio_802154: Fix typo in the clock driver

---

drivers/nrf_radio_802154/platform/random/nrf_802154_random_zephyr.c
nrfx_glue.c
nrfx_glue.h

Switching device parameter to constant.
Signed-off-by: Tomasz Bursztyka <tomasz.bursztyka@linux.intel.com>

drivers: 802154: Device instance are all constant now

---

drivers/nrf_radio_802154/nrf_802154_request_swi.c

Bug description: A `nrf_802154_request_buffer_free` call would return `false` due to not having high enough priority. The required priority comparison would be based on invalid value. Using platform IRQ solves the issue.
Fixes #28360
Signed-off-by: Kwiek, Pawel <pawel.kwiek@nordicsemi.no>

drivers: nrf_radio_802154: Port active_vector_priority_is_high to platform IRQ

---

drivers/nrf_radio_802154/platform/clock/nrf_802154_clock_zephyr.c

When hfclk was switched on and off too fast assert occured due to
enabling still being in progress. Updated nrf_802154_clock_hfclk_stop
to cancel job if it is in progress.
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>

platform: clock: Fixed issue with asserting on clock disabling

---

drivers/nrf_radio_802154/platform/hp_timer/nrf_802154_hp_timer.c

When the nRF 802.15.4 radio driver is used in multiprotocol scenarios,
care must be taken to only use common hardware resources when allowed
explicitly by the arbiter. This patch fixes illegal usage of TIMER0
in the hp_timer module.

drivers: nrf_radio_802154: Fix TIMER0 usage in hp_timer

---

nrfx_config.h
nrfx_glue.h

We need to ensure two things:
1. None of the HAL APIs are inlined.
This is ensured by defining NRF_DECLARE_ONLY and
defining NRF_STATIC_INLINE to nothing
2. Redefining the peripheral and peripheral base defines
after they have been defined by the MDK. As nrfx_glue.h
is included after the MDK, we can do it here.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

boards: nrf52_bsim: nrfx porting for bsim using nrfx directly

---

drivers/nrf_radio_802154/rsch/nrf_802154_rsch.c

In certain conditions, the nRF 802.15.4 driver should immediately
notify RAAL that it processed end of a timeslot. This patch fixes
this notification to perform it only if these conditions are met.

drivers: nrf_radio_802154: Fix RAAL notifications

---

nrfx/hal/nrf_power.h

Since the workaround increases power consumption in System ON IDLE,
it should be applied only when the DC/DC converter for REG0 stage is
to be enabled, not regardless of the applied setting as it was done
so far.

nrf_power: Fix implementation of workaround for nRF52 anomaly 197

---

drivers/nrf_802154_sl_opensource/src/nrf_802154_sl_log.c
drivers/nrf_radio_802154/src/nrf_802154_trx_ppi.c

This commit fixes warning in IEEE 802.15.4 nRF Radio Driver
and linker error in debug build of IEEE 802.15.4 nRF Service
Layer.
Signed-off-by: Czeslaw Makarski <Czeslaw.Makarski@nordicsemi.no>

drivers: Fix warning and linker errors in debug build

---

nrfx_glue.h

Use for DPPI the same mechanism that was so far used for PPI to prevent
assigning of channels and groups used by the Bluetooth controller to
other requesters.
Remove also the additional condition (CONFIG_BT_LL_SW_SPLIT) so that
this mechanism can be used for other Bluetooth controllers as well.

nrfx_glue: Exclude DPPI resources used by BT_CTLR from allocation

---

drivers/nrf_802154_sl_opensource/src/platform/hp_timer/nrf_802154_hp_timer.c

NRF_TIMER0 used in nRF 802.15.4 hp_timer platform example implementation
must be configured to 32-bit width before every use in order for
hp_timer to work correctly.

drivers: nrf_802154_sl_opensource: Restore hp_timer 32-bit width

---

drivers/nrf_802154_sl_opensource/src/nrf_802154_sl_rsch.c

This PR fixes the issue which manifests itself in disabled
NVIC interrupts in SED roles.
Signed-off-by: Czeslaw Makarski <Czeslaw.Makarski@nordicsemi.no>

drivers: nrf_802154_sl_opensource: Tune RSCH priority handling

---

drivers/nrf_802154_sl_opensource/src/nrf_802154_sl_fem.c

This commit fixes naming issues introduced in the MPSL FEM API
implementation in the previous commits.

drivers: nrf_802154_sl_opensource: Fix naming in FEM implementation

---

nrfx_glue.h

PWM SW driver implementation allows now to use RTC instead of TIMER. RTC
uses 3 instead of 2 channels, so adjust PPI channel macros to match
that.

nrfx_glue: Support PWM SW based on RTC

---

drivers/nrf_radio_802154/src/nrf_802154.c
drivers/nrf_radio_802154/src/nrf_802154.h
drivers/nrf_radio_802154/src/nrf_802154_trx.c

This commit introduces nrf_802154_custom_part_of_radio_init callout.
Application can override weak empty implementation to provide some additional
operations to be performed at the beginning of each new timeslot.
In particular, the intention is to enable the injection of special radio
register values during such initialization.

drivers: nrf_radio_802154: Add callout for custom initialization part

---

drivers/nrf_802154_sl_opensource/CMakeLists.txt
drivers/nrf_802154_sl_opensource/nrf_802154_sl_files.cmake
drivers/nrf_radio_802154/CMakeLists.txt
drivers/nrf_radio_802154/nrf_802154_driver_sources.cmake

This commit introduces file list variables providing an abstraction for
files required for IEEE 802.15.4 driver to be built.
The variables are meant to be used by a higher project layer. Introduction
of this variables in current form is an intermediate step for moving IEEE 802.15.4
driver to a separate repository.
Signed-off-by: Pawel Kwiek <pawel.kwiek@nordicsemi.no>

drivers: Add CMake file list variables for IEEE 802.15.4

---

drivers/nrf_802154_serialization/src/platform/zephyr/nrf_802154_spinel_backend_ipc.c

IPC Service allows registering multipe endpoints. Using this
module as serialization backend enables new use cases and simplifies
maintenance of the serialization component.
Signed-off-by: Hubert Miś <hubert.mis@nordicsemi.no>

drivers: 802154_serialization: Use IPC Service as serialization backed

---

drivers/nrf_802154_serialization/src/platform/zephyr/nrf_802154_spinel_backend_ipc.c

This commit removes an unused function and fixes related warning.

drivers: nrf_802514_serialization: Fix unused function warning

---

drivers/nrf_radio_802154/CMakeLists.txt
drivers/nrf_radio_802154/nrf_802154_driver_sources.cmake
drivers/nrf_radio_802154/src/nrf_802154_peripherals_alloc.c
drivers/nrf_radio_802154/src/nrf_802154_peripherals_nrf53.h

Provides bit masks which are intended for use in the nrfx_glue.h
to mark the (D)PPI channels used by the 802.15.4 driver as occupied
and thus unavailable for allocation through nrfx_ppi.
Verification if resources used by the 802.15.4 driver do not overlap
with those used by the mpsl (if mpsl enabled).
Signed-off-by: Adam Zelik <adam.zelik@nordicsemi.no>

nrfx_glue: Reserve PPI/DPPI channels and groups used by 802.15.4 driver

---

drivers/nrf_802154_serialization/CMakeLists.txt

The paths to nrf_802154_serialization could have previously
exceeded the Windows limit on the path name, causing the build
to fail.
The zephyr_library() autogenerate library names, which may result
in very long build paths. Naming the library manually works around
this problem.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>

build: Fix long path build problem on Windows

---

nrfx/drivers/src/nrfx_gpiote.c

GPIOTE channels allocated outside of the context
of the driver are no longer implicitly deallocated
during driver initialization.
Signed-off-by: Nikodem Kastelik <nikodem.kastelik@nordicsemi.no>

nrfx_gpiote: remove channel dealloc from nrfx_gpiote_init

---

nrfx/mdk/nrf5340_network_peripherals.h

This is a temporary change in a file imported from the nrfx repository
and it is supposed to be overwritten by the next update of nrfx.
Signed-off-by: Nikodem Kastelik <nikodem.kastelik@nordicsemi.no>

mdk: fix DPPI_CH_NUM to 32 for nRF5340 Network

---

nrfx/mdk/system_nrf53_approtect.h

This is a temporary change in a file imported from the nrfx repository
and it is supposed to be overwritten by the next update of nrfx.

mdk: Fix bitfield names in system_nrf53_approtect.h

---

nrfx/drivers/src/nrfx_usbreg.c

Clear USBREG events on driver initialization and
prevent spurious USBPWRRDY event right after initialization.

drivers: nrfx_usbreg: clear events on initialization

---

nrfx/drivers/src/nrfx_pwm.c

The whole pin configuration function in the driver should be skipped
when both GPIO and PSEL skip flags are set, but the code that checks
this condition, despite the comment correctly explaining its purpose,
contains an unwanted negation. This commit fixes this embarrassing
copy-paste mistake.

nrfx_pwm: Fix incorrect check that suppresses pin configuration

---

drivers/nrf_802154/sl/include/platform/nrf_802154_irq.h

This commit changes public API of `nrf_802154_irq_init` to allows
passing negative values of `prio` parameter. Negative values will
be used to encode ZLI priority.
Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>

drivers: nrf_802154: nrf_802154_irq_init negative `prio` ZLI

---

nrfx/doc/sphinx/nrfx_api/atomic.rst

Building documentation in .rst format causes warnings due to
missing `nrfx_atomic` which is not used in `hal_nordic`.
Signed-off-by: Nikodem Kastelik <nikodem.kastelik@nordicsemi.no>

nrfx: doc: remove references to nrfx_atomic Doxygen group

---

nrfx/drivers/include/nrfx_qspi.h
nrfx/drivers/src/nrfx_qspi.c

Keep the line high during the custom instruction transfer. Otherwise,
its low level can be interpreted by the memory chip as an active
HOLD#/RESET# signal and in consequence the memory status can be read
incorrectly.
Add also related notes to descriptions of nrfx_qspi_cinstr_xfer() and
nrfx_qspi_lfm_start() to warn users that the default configuration
provided by NRFX_QSPI_DEFAULT_CINSTR() may not always be suitable.

nrfx_qspi: Correct IO3 line level used in nrfx_qspi_mem_busy_check()

---

nrfx/hal/nrf_clock.h

This commit disables the array bounds warning (`-Warray-bounds`) for
the `nrf_clock_is_running` function because GCC 12 and above may report
a false positive due to the size of the write access to the memory
address pointed by the `p_clk_src` argument being variable depending on
the value of the `domain` argument.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
NOTE: This is required for the upcoming Zephyr SDK 0.15.0 release.
p.s. This seems to be due to a GCC bug, I will eventually look into filing an upstream bug once I have a stable test vector; nevertheless, this issue will persist for the GCC 12.x users.

nrfx_clock: Disable array bounds warning for nrf_clock_is_running

---

nrfx/drivers/src/nrfx_usbd.c

Aborting endpoints on suspend contradicts Universal Serial Bus Specification Revision 2.0, 9.1.1.6 Suspended:
* When suspended, the USB device maintains any internal status, including its address and configuration.
The internal status definitely includes any pending USB transfers. Even if the developer wants the transfers to be aborted when bus is suspended (as far as I know, no standard class expects such behavior), USBD driver is the wrong layer to do so.
Remove offending call to usbd_ep_abort_all() in order to allow Zephyr to properly support suspend and get rid of workarounds to multiple suspend related problems that accumulated over the years.
Signed-off-by: Tomasz Moń <tomasz.mon@nordicsemi.no>

nrfx_usbd: Do not abort endpoints on suspend

---

nrfx/drivers/src/nrfx_qspi.c

Add workarounds for anomaly 215 on nRF52840 and anomaly 43 on nRF5340 (Reading QSPI registers after XIP might halt CPU). Also increase the default timeout to 500 ms.

nrfx_qspi: Add workarounds for anomalies 215/nRF52840 and 43/nRF5340

---

nrfx/mdk/nrf91_erratas.h
nrfx/mdk/system_nrf91_approtect.h

Apply corrections that make it possible to disable APPROTECT mechanism (which is enabled by default in hardware) on the nRF91 Series SiPs.
These are temporary changes in files imported from the nrfx repository and they are supposed to be overwritten by the next update of nrfx.

nrfx: mdk: Fix handling of APPROTECT on nRF91

---

nrfx/drivers/include/nrfx_nvmc.h
nrfx/drivers/nrfx_common.h
nrfx/drivers/src/nrfx_nvmc.c
nrfx/hal/nrf_nvmc.h

nvmc: Provide new functions to read and write to flash
For reads both for singular words and buffers,
for writes just for singular words.
--------
drivers: nvmc: Use new hal functions
Use new HAL function to write to flash
(the function is inlined and just performs the same
access for real targets).
This change enables using the driver in the
nrf52_bsim.

NVMC changes for simulation

---

nrfx/drivers/src/nrfx_pwm.c

After receiving NRF_PWM_EVENT_STOPPED event,
driver state should be changed to NRFX_DRV_STATE_INITIALIZED as in irq_handler function.
Fixes issue: https://github.com/zephyrproject-rtos/zephyr/issues/60714

nrfx_pwm: Fix multiple pwm_stopped_check calling

---

nrfx/drivers/src/nrfx_pwm.c

When `NRFX_PWM_NRF52_ANOMALY_109_WORKAROUND_ENABLED` was set nrfy_egu function calls were causing build error as HALY for EGU doesn't exist.

nrfx_pwm: Replace nrfy_egu calls with nrf_egu in PWM driver

---

drivers/nrf_802154/driver/src/nrf_802154_trx.c

Two erratas fixes cannot be applied to the simulated nrf5340. Let's conditionally compile them out.
Note this change is comparable to previous changes to this driver.
Zephyr manifest update test PR: https://github.com/zephyrproject-rtos/zephyr/pull/63208

drivers: nrf_802154: Minor fixes for simulated nrf5340

---

nrfx/drivers/src/nrfx_gpiote.c

GPIOTE driver was incorrectly defining the size of the `pin_flags` array on nRF52820 SoC. The target has 18 pins - as the value of the `P0_PIN_NUM` symbol. However, those pins are not consecutive pins from 0 to 17. The nRF52820 has routed pins 0-8, 14-18, 20 and 28-30.
As a result, accessing pin 18 and above marks in reads/writes that exceed the boundary of the `pin_flags` array. To mitigate that issue, the `MAX_PIN_NUMBER` symbol that is used to define the `pin_flags` array size is now defined as 32 for the nRF52820 device.

nrfx: Fix overflow of pin_flags array on nRF52820 in GPIOTE driver

---

nrfx/drivers/src/nrfx_wdt.c

Since nrfx 3.0.0 it is allowed to initialize the driver without providing an initial configuration. Remove an assertion that still ensures that such configuration was actually provided.

nrfx_wdt: Remove incorrect assertion

---

nrfx/drivers/include/nrfx_qspi.h
nrfx/drivers/src/nrfx_qspi.c

The code that accesses QSPI registers above 0x600 needs to apply workaround for anomaly 215 on nRF52840 or anomaly 43 on nRF5340.
The commit removes check if a custom instruction long transfer is ongoing from deactivate function. The check could trigger anomalies and now it's user responsibility to be sure that custom instruction long transfer has ended otherwise it will be interrupted.
Change affects behaviour of nrfx_qspi_uinit() and nrfx_qspi_deactivate() what is mentioned in documentation for that functions.

nrfx_qspi: Correct use of workaround for anomaly 215 and 43 in nrfx_qspi

---

nrfx/helpers/nrfx_gppi_dppi_ppib.c
nrfx/soc/interconnect/ipct/nrfx_interconnect_ipct.h

Remove dependency on the nrfx_atomic component that is not present in hal_nordic.
Add missing `soc/` part in one interconnect header inclusion.
These are temporary changes in files imported from the nrfx repository and they are supposed to be overwritten by the next update of nrfx.

nrfx: Fix compilation failures in nrfx_gppi_dppi_ppib.c

---

nrfx/hal/nrf_common.h

Function was not covering whole DMA capable regions.

hal: nrf_common: Fix address checking in nrf_dma_accessible_check

---

nrfx/drivers/src/nrfx_uarte.c
nrfx/mdk/nrf54l15_application_peripherals.h
nrfx/mdk/nrf54l15_enga_application_peripherals.h
nrfx/mdk/nrf54l15_enga_flpr_peripherals.h
nrfx/mdk/nrf54l15_flpr_peripherals.h

3 fixes:
- Fix MDK for nrf54l15 to use correct values for MAX EasyDMA transfer length for UARTE. Without this fix transfers are limited to 127 bytes.
- Add clearing of RX events after blocking RX disable so that receiver starts with clean state on the following RX enabling.
- Fix race condition in the interrupt handler.

Fixes for nrfx_uarte

---

nrfx/haly/nrfy_grtc.h

Use the NRFY static inline macro for the nrfy code, so this code works properly for simulation too.

haly grtc: Use appropriate static inline macro

---

nrfx/hal/nrf_cache.h

Add function for getting LINEADDR register content.

nrfx: hal: nrf_cache: Add nrf_cache_lineaddr_get

---

nrfx/hal/nrf_ppib.h

Enumerate values need to fit in the range of
int if we are to be strictly standad compliant.
But for this emum in question, its highest value
is generated from a bitmask of the 31st bit,
which, as a possitive number is out the int range.
This can cause warnings for compilers
which are run in a pedantic enough mode.
GCC is one of this, producing a warning like:
"warning: ISO C restricts enumerator values to range of ‘int’" when run with "-Wpedantic"
Let's disable these warnings for this enum definition when building for GCC.
Apart from this warning, GCC seems to properly handle this case.
Note that as this definitions are in headers, the issue is triggered when a user tries to compile their code with the corresponding warnings enabled.
---
Zephyr test PR: …

PPIB: Strict C compliance warning waive

---

nrfx/hal/nrf_saadc.h

Add support for 8bit transfers for all devices in nRF54 family.

nrfx: hal: saadc: Expand support for 8bit transfers in nRF54

---

nrfx/hal/nrf_auxpll.h

Add some additional APIs for AUXPLL that are needed/useful in the Zephyr context.

nrfx: hal: auxpll: add additional APIs

---

nrfx/drivers/src/nrfx_spim.c
nrfx/haly/nrfy_spim.h

When CTRLSEL mechanism is present, GPIO registers cannot preserve pin state when SPIM is disabled. This can cause glitches on the bus. Enabling and disabling SPIM instance externally can mitigate this.

nrfx: allow enabling SPIM externally when CTRLSEL is present

---

nrfx/drivers/src/nrfx_gpiote.c

Move enabling GPIOTE port interrupt from GPIOTE initialization function to pin trigger enable function. This is due to the fact that GPIO is by default enabled in Zephyr which causes tests to fail on Moonlight's FLPR, because APP handles events that should be handled by FLPR.

nrfx: drivers: nrfx_gpiote: move enabling GPIOTE port interrupt

---

nrfx/soc/interconnect/dppic_ppib/nrfx_interconnect_dppic_ppib_lumos.h

The PPIB instances were hardcoded to use the secure peripheral. Using the dppic_ppib helper from nonsecure lead to secure faults.
Remove the `_S` suffix to use the correct peripheral instance both when building for secure and nonsecure.

nrfx: Fix dppic_ppib for Nonsecure

---

drivers/nrf_wifi/hw_if/hal/src/hal_api.c

Fix for boot signature check never returning failure on timeout.

nrf_wifi : Fix fw boot signature check timeout

---

nrfx/hal/nrf_radio.h

There are new symbols for new configuration in nRF54L15.

nrfx: Add support for new 4Mbit symbols in radio in nRF54L15

---

nrfx/drivers/include/nrfx_comp.h
nrfx/drivers/include/nrfx_lpcomp.h
nrfx/drivers/src/nrfx_lpcomp.c
nrfx/hal/nrf_comp.h
nrfx/haly/nrfy_lpcomp.h

API for Low Power Comparator and regular comparator used different naming. LPCOMP API also lacked
`nrfx_lpcomp_reconfigure` and `nrfx_lpcomp_sample` functions, which are now provided.
New function `nrfx_lpcomp_start` extends `nrfx_lpcomp_enable` with shorts and events parameters. `_enable` now calls `_start` with zeros as arguments.
New function `nrfx_lpcomp_stop` replaces `nrfx_lpcomp_disable`. `_disable` is still provided, but simply calls` _stop`.
Added new HALY function `nrfy_lpcomp_sample` that return sample as `uint32_t`.
Regular comp mode setting is patched.

nrfx: lpcomp: align nrfx_lpcomp to Zephyr shim and patch comp modes

---

nrfs/helpers/dvfs_oppoint.c

Medlow DVFS oppoint was using current limit mode FICR index (5) since there was no other that was supporting 128MHz. Now medlow index in FICR (2) is using 128MHz so this one needs to be used. This also fixes on all idle issues when switching to medlow DVFS oppoint.

nrfs: update medlow oppoint FICR trim index

---

drivers/nrf_802154/common/include/nrf_802154.h
drivers/nrf_802154/common/include/nrf_802154_config.h
drivers/nrf_802154/common/include/nrf_802154_const.h
drivers/nrf_802154/driver/src/mac_features/ack_generator/nrf_802154_ack_data.c
drivers/nrf_802154/driver/src/mac_features/nrf_802154_frame_parser.h
drivers/nrf_802154/driver/src/mac_features/nrf_802154_ie_writer.c
drivers/nrf_802154/driver/src/mac_features/nrf_802154_ie_writer.h
drivers/nrf_802154/driver/src/mac_features/nrf_802154_security_writer.c
drivers/nrf_802154/driver/src/nrf_802154.c
drivers/nrf_802154/driver/src/nrf_802154_core.c
drivers/nrf_802154/driver/src/nrf_802154_encrypt.c

nrf_802154: rev 559b3d38a1f490371ebac659959d2eebda078b58

---

drivers/nrf_wifi/fw_if/umac_if/src/cmd.c

Country code is expected to be a string. But the build time macro is not passing a string. Use `STRINGIFY` to fix this.

nrf_wifi: Stringify country code before passing to firmware

---

nrfx/drivers/src/nrfx_lpcomp.c

The LPCOMP driver currently only disables all interrupts when first initialized. starting or reconfiguring the comparator from here only ever enables additional interrupts using nrfy_lpcomp_int_enable() which results in it not being possible to disable an interrupt source when it has been enabled.
This commit adds a call to nrfy_lpcomp_int_disable() which disables all interrupts when the comparator is stopped using nrfx_lpcomp_stop(). A new interrupt mask is provided by the next call to nrfx_lpcomp_start() .

nrfx: drivers: nrfx_lpcomp: dis all interrupts on stop

---

drivers/nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h
drivers/nrf_wifi/fw_if/umac_if/inc/fmac_promisc.h
drivers/nrf_wifi/fw_if/umac_if/src/fmac_promisc.c
drivers/nrf_wifi/fw_if/umac_if/src/rx.c

This set of changes brings in promiscuous mode filtering support in the driver. Since, firmware woulld be unable to filter packets in the case of promiscuous mode as it would lead to connection issues, filtering support is moved to the driver for promiscuous mode.

nrf_wifi: Bring in Promiscuous mode filtering support in driver

---

drivers/nrf_wifi/fw_if/umac_if/inc/offload_raw_tx/fmac_structs.h
drivers/nrf_wifi/fw_if/umac_if/src/event.c
drivers/nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
drivers/nrf_wifi/fw_if/umac_if/src/offload_raw_tx/fmac_api.c

If parameters is not set correctly return error for regulatory domain. Check current regulatory domain.

drivers: nrf_wifi: Add check for wrong regulatory domain

---

drivers/nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h
drivers/nrf_wifi/fw_if/umac_if/src/rx.c

Potential fix for a warning `RX deinit called for unmapped RX buffer`.

wifi: Fix Rx processing

---

drivers/nrf_wifi/fw_if/umac_if/src/cmd.c

This print is not informational and is only necessary during debugging to ensure that this feature is enabled.
Convert to debug level.

nrf_wifi: Use debug level

---

nrfx/drivers/include/nrfx_ppib.h
nrfx/hal/nrf_common.h

drivers nrfx_ppib: Use appropriate static inline macro
Use the NRFX static inline macro for the nrfx code,
so this code works properly for simulation too.
-----
hal: nrf_common: Add missing prototypes
We need prototypes for all functions so that when NRF_DECLARE_ONLY
is set we still at least get them.
Related to https://github.com/zephyrproject-rtos/zephyr/pull/83280
Zephyr test PR: https://github.com/zephyrproject-rtos/zephyr/pull/83302

2 header fixes

---

nrfx/samples/src/nrfx_egu/sample.yaml
nrfx/samples/src/nrfx_gppi/fork/sample.yaml
nrfx/samples/src/nrfx_gppi/one_to_one/sample.yaml
nrfx/samples/src/nrfx_pwm/common_mode/sample.yaml
nrfx/samples/src/nrfx_pwm/grouped_mode/sample.yaml
nrfx/samples/src/nrfx_rng/sample.yaml
nrfx/samples/src/nrfx_saadc/advanced_blocking/sample.yaml
nrfx/samples/src/nrfx_saadc/advanced_non_blocking_internal_timer/sample.yaml
nrfx/samples/src/nrfx_saadc/maximum_performance/sample.yaml
nrfx/samples/src/nrfx_saadc/simple_blocking/sample.yaml
nrfx/samples/src/nrfx_saadc/simple_non_blocking/sample.yaml
nrfx/samples/src/nrfx_spim/blocking/sample.yaml
nrfx/samples/src/nrfx_spim/non_blocking/sample.yaml
nrfx/samples/src/nrfx_spim_spis/advanced_non_blocking/sample.yaml
nrfx/samples/src/nrfx_spim_spis/non_blocking/sample.yaml
nrfx/samples/src/nrfx_temp/blocking/sample.yaml
nrfx/samples/src/nrfx_temp/non_blocking/sample.yaml
nrfx/samples/src/nrfx_timer/counter/sample.yaml
nrfx/samples/src/nrfx_timer/timer/sample.yaml
nrfx/samples/src/nrfx_twim_twis/tx_rx_blocking/sample.yaml
nrfx/samples/src/nrfx_twim_twis/tx_rx_non_blocking/sample.yaml
nrfx/samples/src/nrfx_twim_twis/txrx/sample.yaml
nrfx/samples/src/nrfx_twim_twis/txtx/sample.yaml
nrfx/samples/src/nrfx_uarte/rx_double_buffered/sample.yaml
nrfx/samples/src/nrfx_uarte/tx_rx_non_blocking/sample.yaml

Twister no longer supports space-separated lists.

nrfx: samples: use native YAML lists

---

.gitignore

Add binary blobs to `.gitignore`, since they should not be committed and clutter up git status output.

.gitignore: ignore binary blobs pulled by `west blobs`

---

nrfx/drivers/include/nrfx_cracen.h
nrfx/drivers/src/nrfx_cracen.c
nrfx/hal/nrf_cracen_cm.h
nrfx/hal/nrf_cracen_rng.h
nrfx/helpers/nrf_cracen_cm_dma.h

Introduce a new CRACEN CTR_DRBG pseudo random driver which uses the CRACEN TRNG and Cryptomaster HW.
Note this driver is only intended for nRF54L devices, and meant to be used when nrf security is not in use. That is for builds with plain vanilla Zephyr (no NCS) or other SW builds with nrfx but without Zephyr or NCS.
The first two commits are just bringing those 2 hals ahead of the release. Those files are taken as is.

Add new cracen_ctr_drbg driver

---

nrfx/drivers/src/nrfx_usbreg.c

Clear USBPWRRDY event on driver initialization and prevent spurious event right after initialization.
This was already fixed in commit cad21db72a61
("drivers: nrfx_usbreg: clear events on initialization") and the fix was removed in commit 2591a2b6006a
("nrfx: Update to version 3.9.0")
.
Partially reinstate the fix. Do not clear all events, as this prevents the USBDETECTED event from being fired if the cable was already connected during initialization.

drivers: nrfx_usbreg: clear USBPWRRDY event on initialization

---

nrfx/hal/nrf_gpio.h

So that we can query the configured drive mode.

hal: gpio: add nrf_gpio_pin_drive_get()

---

nrfx/drivers/src/nrfx_rramc.c

When NRFX_ASSERT is disabled, Clang complains that the function are unused. Fix this by declaring them as unused.

nrfx: drivers: rramc: Declare functions as unused

---

drivers/nrf_802154/sl/include/nrf_802154_sl_utils.h

Add define guards to min and max so that they don't collide with the upstream ones.

drivers: nrf_802154: add define guard to min and max
